all: beer cesar vigenere

beer: beer.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o beer beer.c -lcc50 -lm

cesar: cesar.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o cesar cesar.c -lcc50 -lm

vigenere: vigenere.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o vigenere vigenere.c -lcc50 -lm